SET SCHEMA CINE;

CREATE TABLE KUNDEN (
KDID			CHAR(5)			NOT NULL
GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
VORNAME			VARCHAR(50),
NACHNAME		VARCHAR(50),
EMAIL			VARCHAR(50)		NOT NULL,
PASSWORT		VARCHAR(50)		NOT NULL,
GEBURTSDATUM	DATE,
GESCHLECHT		VARCHAR(50),
BUNDESLAND		VARCHAR(50),
ORT				VARCHAR(50),
PLZ				VARCHAR(50),
STRASSE			VARCHAR(50),
HAUSNUMMER		CHAR(5),
PRIMARY KEY	(KDID),
);

CREATE TABLE WARENKORB (
WKID			INTEGER			NOT NULL,
ERSTELLDATUM	DATE			NOT NULL	DEFAULT CURRENT DATE,
KDID			CHAR(5)			NOT NULL,
PRIMARY KEY	(WKID),
FOREIGN KEY	(KDID) REFERENCES KUNDEN (KDID)
);

CREATE TABLE BESTELLUNG (
BESTELLID		INTEGER			NOT NULL,
BESTELLDATUM	DATE			NOT NULL	DEFAULT CURRENT DATE,		
LIEFERDATUM		DATE,
GESAMTPREIS		DECIMAL(6, 2),	
KDID			INTEGER			NOT NULL,
PRIMARY KEY (BESTELLID),
FOREIGN KEY	(KDID) REFERENCES KUNDEN (KDID)
);

CREATE TABLE FILM (
FILMID			INTEGER   		NOT NULL,
TITEL			VARCHAR(50),
BESCHREIBUNG	VARCHAR(50),
GENRE			VARCHAR(50),
REGIE			VARCHAR(50),
HAUPTDARSTELLER	VARCHAR(50),
PREIS			DECIMAL(6, 2)	NOT NULL,
PRIMARY KEY (FILMID)
);

CREATE TABLE FILMWARENKORB (
FILMID		INTEGER			NOT NULL,
WKID		INTEGER			NOT NULL,
PRIMARY KEY	(PNR, WKID),
FOREIGN KEY	(PNR) REFERENCES FILM (FILMID),
FOREIGN KEY	(WKID) REFERENCES WARENKORB (WKID)
);

CREATE TABLE FILMBESTELLUNG (
FILMID		INTEGER			NOT NULL,
BESTELLID	INTEGER			NOT NULL,
PRIMARY KEY	(PNR, BESTELLID),
FOREIGN KEY	(PNR) REFERENCES FILM (FILMID),
FOREIGN KEY	(BESTELLID) REFERENCES BESTELLUNG (BESTELLID)
);
