/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-08-14 18:50:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class WelcomeView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Welcome to CINE</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/WelcomeView.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"background\">\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<form method=\"get\" action=\"../jsp/WelcomeAppl.jsp\">\r\n");
      out.write("\t\t\t\t<table class=\"oben\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"obenLinks\" align=\"left\"><img class=\"logo\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"CINE\" src=\"../img/logoCINE.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"obenRechts\" align=\"right\"><input class=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" name=\"anmelden\" value=\"Anmelden\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\" class=\"untenLinks\"><object width=\"704\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"448.8\" type=\"video/mp4\" \r\n");
      out.write("\t\t\t\t\t\t\t\tdata=\"../video/StarWars_VII_HD_Deutsch.mp4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<param name=\"volume\" value=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<param name=\"quality\" value=\"high\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<param name=\"scale\" value=\"exactfit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<param name=\"bgcolor\" value=\"black\">\r\n");
      out.write("\t\t\t\t\t\t\t</object></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\" class=\"untenRechts\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"font\">Holen Sie das Kino in Ihr Wohnzimmer</h1> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"font\">Sie haben noch kein Konto?</h3> <br> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"button\" type=\"submit\" name=\"registrieren\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Jetzt Registrieren\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
